// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static boolean imageOnChange(IContext context, myfirstmodule.proxies.CustomerImage _image)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Image", _image == null ? null : _image.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MyFirstModule.ImageOnChange", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_DeleteAll(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MyFirstModule.MB_DeleteAll", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean onAccept(IContext context, myfirstmodule.proxies.Image _image)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Image", _image == null ? null : _image.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MyFirstModule.OnAccept", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean onChange(IContext context, system.proxies.Image _image)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Image", _image == null ? null : _image.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MyFirstModule.OnChange", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean onRemove(IContext context, system.proxies.Image _image)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Image", _image == null ? null : _image.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MyFirstModule.OnRemove", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}